openapi: 3.2.0
info:
  title: DigitalCommunity Ola Merchant Post API
  description: To use this API, you need to have been first been issued a username and password by RICS.
  version: v1
security:
- Bearer: []
tags:
- name: OlaMerchantPost
paths:
  /api/OlaMerchantPost:
    post:
      tags:
      - OlaMerchantPost
      responses:
        '200':
          description: Success
      summary: Create api ola merchant post
      x-summary-source: derived
      operationId: postApiOlaMerchantPost
      x-operation-id-source: derived
components:
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please enter into field the word 'Bearer' following by space and JWT
      name: Authorization
      in: header
