openapi: 3.2.0
info:
  title: DigitalCommunity Azure Storage API
  description: To use this API, you need to have been first been issued a username and password by RICS.
  version: v1
security:
- Bearer: []
tags:
- name: AzureStorage
paths:
  /api/AzureStorage/GetRegulationDeclarationDocuments:
    get:
      tags:
      - AzureStorage
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RegulationDeclaration'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RegulationDeclaration'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RegulationDeclaration'
        '204':
          description: No Content
        '400':
          description: Bad Request
      deprecated: true
      summary: Get api azure storage get regulation declaration documents
      x-summary-source: derived
      operationId: getApiAzureStorageGetRegulationDeclarationDocuments
      x-operation-id-source: derived
  /api/AzureStorage/DeleteRegulationDeclarationDocuments:
    delete:
      tags:
      - AzureStorage
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RegulationDeclaration'
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RegulationDeclaration'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RegulationDeclaration'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RegulationDeclaration'
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: true
      summary: Delete api azure storage delete regulation declaration documents
      x-summary-source: derived
      operationId: deleteApiAzureStorageDeleteRegulationDeclarationDocuments
      x-operation-id-source: derived
  /api/AzureStorage/StoreRegulationDeclarationDocument:
    post:
      tags:
      - AzureStorage
      parameters:
      - name: RowKey
        in: query
        schema:
          type: string
      - name: SchemeId
        in: query
        schema:
          type: string
      - name: StorageUrl
        in: query
        schema:
          type: string
      - name: SharepointPath
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: true
      summary: Create api azure storage store regulation declaration document
      x-summary-source: derived
      operationId: postApiAzureStorageStoreRegulationDeclarationDocument
      x-operation-id-source: derived
  /api/AzureStorage/UploadFile:
    post:
      tags:
      - AzureStorage
      parameters:
      - name: containerName
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: true
      summary: Create api azure storage upload file
      x-summary-source: derived
      operationId: postApiAzureStorageUploadFile
      x-operation-id-source: derived
  /api/AzureStorage/DownloadFile:
    get:
      tags:
      - AzureStorage
      parameters:
      - name: fileUrl
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: true
      summary: Get api azure storage download file
      x-summary-source: derived
      operationId: getApiAzureStorageDownloadFile
      x-operation-id-source: derived
  /api/AzureStorage/DeleteLogData:
    post:
      tags:
      - AzureStorage
      parameters:
      - name: tableName
        in: query
        schema:
          type: string
      - name: toDate
        in: query
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: true
      summary: Create api azure storage delete log data
      x-summary-source: derived
      operationId: postApiAzureStorageDeleteLogData
      x-operation-id-source: derived
components:
  schemas:
    RegulationDeclaration:
      type: object
      properties:
        rowKey:
          type:
          - string
          - 'null'
        schemeId:
          type:
          - string
          - 'null'
        storageUrl:
          type:
          - string
          - 'null'
        sharepointPath:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please enter into field the word 'Bearer' following by space and JWT
      name: Authorization
      in: header
